config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#home"
  get 'pages/home', to: 'pages#home'
  resources :recipes do 
    resources :comments , only: [:create]
  end


  get '/signup', to: 'chefs#new'
  resources :chefs, expect: [:new]
  get '/login' , to: 'sessions#new'
  post 'login' , to: 'sessions#create'
  delete '/logout' , to: 'sessions#destroy'

  resources :ingrediants, except: [:destroy]
end

app/models/recipe.rb
class Recipe< ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true, length: {minimum: 20}
    belongs_to :chef
    validates :chef_id, presence: true
    default_scope -> {order(updated_at: :desc)}
    has_many :recipe_ingrediants
    has_many :ingrediants , through: :recipe_ingrediants
    has_many :comments, dependent: :destroy
end

app/controllers/recipes_controller.rb
class RecipesController< ApplicationController
before_action :set_recipe, only: [:show, :edit, :update]
before_action :require_user, except: [:index,:show]
before_action :require_same_user, only: [:edit,:update,:destroy]

    def index
        @recipes=Recipe.paginate(page: params[:page],per_page: 5)
    end
    def new
        @recipe=Recipe.new
    end

    def create
        @recipe=Recipe.new(recipe_params)
        @recipe.chef=current_chef
        if @recipe.save
            flash[:success]="Recipe was created Successfully"
            redirect_to recipe_path(@recipe)
        else
            render 'new' , status: :unprocessable_entity
        end
    end


    def show
        @comment=Comment.new
        @comments=@recipe.comments.paginate(page: params[:page],per_page: 10)
    end

    def edit
    end


    def update
        if @recipe.update(recipe_params)
            flash[:success]="Recipe was updates successfully"
            redirect_to recipe_path(@recipe)
        else
            render 'edit' , status: :unprocessable_entity
        end
    end


    def destroy
        @recipe=Recipe.find(params[:id]).destroy
        flash[:success]="Recipe was deleted successfully"
        redirect_to recipes_path , status: :see_other
    end

private

def set_recipe
    @recipe=Recipe.find(params[:id])
end

def recipe_params
    params.require(:recipe).permit(:name,:description, ingrediant_ids: [])
end

def require_same_user
    if current_chef != @recipe.chef and !current_chef.admin?
        flash[:danger]="You can only edit or delete your own recipes"
        redirect_to recipes_path
    end
end

end

app/views/recipes/_form.html.erb
<%= render 'shared/error', obj: @recipe%>

<div class="row">
    <div class="col-md-12">
        <%= form_for(@recipe, :html => {class: "form-horizontal",role: "form"}) do |f|%>
            <div class="form-group">
                <div class="control-label col-md-8">
                    <%=f.label :name%>
                </div>
                <div class= "col-md-10">
                    <%= f.text_field :name , class: "form-control", placeholder: "Name of recipe",autofocus: true%>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-8">
                    <%=f.label :description%>
                </div>
                <div class="col-md-10">
                    <%=f.text_area :description, rows: 10, class: "form-control",placeholder: "Enter steps to create recipe"%>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-md-offset-2 col-md-8">
                        <%=f.collection_check_boxes :ingrediant_ids , Ingrediant.all, :id, :name do |i|%>
                            <%i.label(class: "checkbox-inline input_checkbox") {i.check_box(class: "checkbox") +i.text}%>
                        <%end%>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-12">
                    <%=f.submit class: "btn btn-primary btn-md btn-xlarge"%>
                    <%=link_to "Return to Recipes", recipes_path, class: "btn btn-primary btn-md btn-xlarge"%>
                </div>
            </div>

        <%end%>
    </div>
</div>

app/views/recipes/_recipe.html.erb
<br>

<% obj.each do |recipe|%>
    <br><br>
    <div class="row">
        <div class= "col-md-3">
            <section class="center">
                <%= gravatar_for(recipe.chef, size: 110)%>
            </section>
        </div>
        <div class="col-md-8 well">
            <h4><%=link_to recipe.name, recipe_path(recipe)%></h4>
            <br>
            <p>
                <div class="float-end"><span class="quiet"><small>Created <%= time_ago_in_words(recipe.created_at) %> ago by <%=recipe.chef.name.capitalize%><br><%=pluralize(recipe.comments.count,'Comment')%> </small></span></div>
            </p>
            <p><%=truncate(recipe.description, length: 70)%></p>
            <%if recipe.ingrediants.any? %>
                <p>Ingrediants: <%=render recipe.ingrediants%></p>
            <%end%>
            <%if logged_in? && (current_chef==recipe.chef || current_chef.admin?)%>
            <div class="float-end well1">
                <%=link_to "Edit this Recipe", edit_recipe_path(recipe), class: "btn btn-primary btn-md btn-xlarge" %>
                 <%=link_to "Delete this recipe", recipe_path(recipe), class:"btn btn-primary btn-xs btn-xlarge", 
            data: {"turbo-method": :delete}, method: :delete%>
            </div>
            <%end%>
        </div>
    </div>
<%end%>

app/views/recipes/edit.html.erb
<%=render 'shared/page_title', title: "Edit an exisiting new recipe"%>

<%=render 'recipes/form'%>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "listing  all the recipes"%>
<br>
<div align="center">
    <%= will_paginate%>
</div>
<%=render 'recipes/recipe', obj: @recipes%>
<div align="center">
    <%= will_paginate%>
</div>

app/views/recipes/new.html.erb
<%=render 'shared/page_title', title: "create a new recipe"%>


<%= render 'recipes/form'%>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name%>
<div class="well col-md-12 col-md-offset-4">
    <h2 class="center desc">Steps: </h2>
    <h4><%=simple_format(@recipe.description)%></h4>
    <%if @recipe.ingrediants.any?%>
        <p>Ingrediants: <%=render @recipe.ingrediants%></p>
    <%end%>
    <hr/>
    <%if logged_in?%>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <%= form_for([@recipe, @comment] , :html => {class: "form-horizontal",role: "form"}) do |f|%>
                    <div class="form-group">
                        <div class="control-label col-md-8">
                            <%=f.label :"Enter your Comment Below:"%>
                        </div>
                        <div class="col-md-10">
                            <%=f.text_area :description, rows: 4, class: "form-control",placeholder: "Enter Comment:"%>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-12">
                            <%=f.submit "Enter Comment", class: "btn btn-primary btn-md btn-xlarge"%>
                        </div>
                    </div>
                <%end%>
            </div>
        </div>
    <%end%>
     
    <hr/>

    <%if @recipe.comments !=0 %>
        <div class ="row">
            <div class="col-md-8 col-md-offset-2">
                <h3>Comments: </h3>
                <br>
                <div id="messages">
                    <%=render partial: "comments/comments" , object: @comments%>
                </div>
            </div>
        </div>
    <%else%>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <h3>No comments Yet!</h3>
            </div>
        </div>
    <%end%>
    <br>
    <hr/>
    <div class="col-md-12 col-md-offset-4 well1 center">
        <%if logged_in? && (current_chef==@recipe.chef || current_chef.admin?) %>      
                <%=link_to "Edit this Recipe", edit_recipe_path(@recipe), class: "btn btn-primary btn-xs btn-xlarge"%>
                <%=link_to "Delete this recipe", recipe_path(@recipe), class:"btn btn-primary btn-xs btn-xlarge", 
            data: {"turbo-method": :delete}, method: :delete%>
        <%end%>
            <%=link_to "Return to Recipes", recipes_path, class: "btn btn-primary btn-xs btn-xlarge" %>
    </div>
    <br>
    <div class="center">
        <p class="center">
            <em>Created by:</em>
        </p>
        <p class="center">
            <%= gravatar_for(@recipe.chef)%>
        </p>
        <p class="center">
            
            <%=link_to @recipe.chef.name.capitalize , chef_path(@recipe.chef)%></small>
            <div class="center"><%=time_ago_in_words(@recipe.created_at)%> ago</div>
        </p>
    </div> 
</div>