config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#home"
  get 'pages/home', to: 'pages#home'
  resources :recipes do 
    resources :comments , only: [:create]
  end


  get '/signup', to: 'chefs#new'
  resources :chefs, expect: [:new]
  get '/login' , to: 'sessions#new'
  post 'login' , to: 'sessions#create'
  delete '/logout' , to: 'sessions#destroy'

  resources :ingrediants, except: [:destroy]
end

app/models/ingrediant.rb
class Ingrediant < ApplicationRecord
    validates :name, presence: true, length: {minimum: 3, maximum: 25}
    validates_uniqueness_of :name
    has_many :recipe_ingrediants
    has_many :recipes, through: :recipe_ingrediants
end

app/controllers/ingrediants_controller.rb
class IngrediantsController < ApplicationController
    before_action :set_ingredients, only: [:show,:edit,:update]
    before_action :require_admin, except: [:show,:index]

    def new
        @ingrediant=Ingrediant.new
    end

    def create
        @ingrediant=Ingrediant.new(ingrediant_params)
        if @ingrediant.save
            flash[:success]="Ingrediant was added Successfully"
            redirect_to ingrediant_path(@ingrediant)
        else
            render 'new' , status: :unprocessable_entity
        end
    end

    def update
        if @ingrediant.update(ingrediant_params)
            flash[:success]="Ingrediant was updated successfully"
            redirect_to ingrediant_path(@ingrediant)
        else
            render 'edit' , status: :unprocessable_entity
        end
    end

    def show
        @ingrediant_recipes=@ingrediant.recipes.paginate(page: params[:page], per_page: 5)
    end

    def index
        @ingrediants=Ingrediant.paginate(page: params[:page], per_page: 6)
    end

    private

    def set_ingredients
        @ingrediant=Ingrediant.find(params[:id])
    end


private

def ingrediant_params
    params.require(:ingrediant).permit(:name)
end

def require_admin
    if !logged_in? || (logged_in? and !current_chef.admin?)
        flash[:danger]="Only admin user can perform this action"
        redirect_to ingrediants_path
    end
end

end

app/views/ingrediants/_form.html.erb
<%= render 'shared/error', obj: @ingrediant%>

<div class="row">
    <div class="col-md-12">
        <%= form_for(@ingrediant, :html => {class: "form-horizontal",role: "form"}) do |f|%>
            <div class="form-group">
                <div class="control-label col-md-8">
                    <%=f.label :name%>
                </div>
                <div class= "col-md-10">
                    <%= f.text_field :name , class: "form-control", placeholder: "Enter Ingrediant",autofocus: true%>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-12">
                    <%=f.submit(@ingrediant.new_record? ? "Add Ingrediant" : "Edit Ingrediant" , class: "btn btn-primary btn-md btn-xlarge")%>
                    <%=link_to "Return to Ingrediants", ingrediants_path, class: "btn btn-primary btn-md btn-xlarge"%>
                </div>
            </div>

        <%end%>
    </div>
</div>

app/views/ingrediants/_ingrediant.html.erb
<span class="badge"><%=link_to ingrediant.name,ingrediant_path(ingrediant) %></span>

app/views/ingrediants/edit.html.erb
<%=render 'shared/page_title', title: "Edit Ingrediant"%>
<br>

<%=render 'form'%>

app/views/ingrediants/index.html.erb
<%= render 'shared/page_title' , title: "Available Ingrediants"%>
<br>

<div align="center">
    <%= will_paginate%>
</div>


<div align="center">
    <%@ingrediants.each do |ing|%>
        <ul class="listing">
            <div class="row">
                <div class="col-md-12 col-md-offset-2">
                    <br>
                    <li class="chef-title"><%=link_to ing.name.capitalize, ingrediant_path(ing)%></li>
                    <li><%=pluralize(ing.recipes.count, "recipe") if ing.recipes%></li>
                    <%if logged_in? &&current_chef.admin?%>
                        <%=link_to "Edit this ingrediant", edit_ingrediant_path(ing)%>
                    <%end%>    
                </div>
            </div>
        </ul>
    <%end%>
</div>

<div align="center">
    <%= will_paginate%>
</div>

app/views/ingrediants/new.html.erb
<%=render 'shared/page_title', title: "New Ingrediant"%>
<br>

<%=render 'form'%>

app/views/ingrediants/show.html.erb
<%=render 'shared/page_title', title: "#{@ingrediant.name}"%>

<br>
<%if @ingrediant.recipes.count !=0 %>
    <h4 align="center">Recipe's Containing <%=@ingrediant.name.capitalize%></h4>
    <div class="col-md-12 center">
    <%=will_paginate @ingrediant_recipes%>
    </div>
    <%=render 'recipes/recipe', obj: @ingrediant_recipes%>
    <div align="center">
    <%=will_paginate @ingrediant_recipes%>
    </div>
<%else%>
    <h4 align="center">No recipes Yet</h4>
<%end%>
<hr/>
<br>